folders <- c("raw_data", "clean_data", "scripts", "results", "plots", "Tasks")
sapply(folders, dir.create, showWarnings = FALSE)
df <- read.csv("raw_data/patient_info.csv", stringsAsFactors = FALSE)
df <- read.csv("raw_data/patient_info.csv", stringsAsFactors = FALSE)
str(df)
summery(df)
str(df)
summary(df)
df$age <- as.numeric(df$age)
df$gender <- as.factor(df$gender)
df$smoker <- as.factor(df$smoker)
df$smoking_status_binary <- ifelse(df$smoker == "Yes", 1, 0)
df$smoking_status_binary <- factor(df$smoking_status_binary, levels = c(0, 1))
view(patient_info.csv)
View(data)
View(patient_info.csv)
write.csv(df, file = "clean_data/patient_info_clean.csv", row.names = FALSE)
